### ISSUE TITLE
 Max Retries Exceeded for URL

### ISSUE THREAD

**Issue by clarkjw4** [clarkjw4/freqtrade#12]
```
Traceback (most recent call last):
  File "/Users/John/Documents/GitHub/freqtrade/.env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/John/Documents/GitHub/freqtrade/.env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/Users/John/Documents/GitHub/freqtrade/.env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/Users/John/Documents/GitHub/freqtrade/.env/lib/python3.6/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/Users/John/Documents/GitHub/freqtrade/.env/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:748)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/John/Documents/GitHub/freqtrade/.env/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/John/Documents/GitHub/freqtrade/.env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/John/Documents/GitHub/freqtrade/.env/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='bittrex.com', port=443): Max retries exceeded with url: /Api/v2.0/pub/market/GetTicks?marketName=BTC-MONA&tickInterval=fiveMin&_=1508197628000 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:748)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main.py", line 302, in <module>
    app(_CONF)
  File "./main.py", line 275, in app
    _process()
  File "./main.py", line 44, in _process
    trade = create_trade(float(_CONF['stake_amount']), exchange.EXCHANGE)
  File "./main.py", line 204, in create_trade
    if get_buy_signal(_pair):
  File "/Users/John/Documents/GitHub/freqtrade/analyze.py", line 264, in get_buy_signal
    dataframe = analyze_ticker(pair)
  File "/Users/John/Documents/GitHub/freqtrade/analyze.py", line 252, in analyze_ticker
    data = get_ticker(pair, minimum_date)
  File "/Users/John/Documents/GitHub/freqtrade/analyze.py", line 35, in get_ticker
    data = requests.get(url, params=params, headers=headers).json()
  File "/Users/John/Documents/GitHub/freqtrade/.env/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/John/Documents/GitHub/freqtrade/.env/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/John/Documents/GitHub/freqtrade/.env/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/John/Documents/GitHub/freqtrade/.env/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/John/Documents/GitHub/freqtrade/.env/lib/python3.6/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='bittrex.com', port=443): Max retries exceeded with url: /Api/v2.0/pub/market/GetTicks?marketName=BTC-MONA&tickInterval=fiveMin&_=1508197628000 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:748)'),))
```

**Comment by WaterKH** [comment]
This issue seems fixed with a previous unknown update
