### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value

### ISSUE THREAD

**Issue by clarkjw4** [clarkjw4/freqtrade#13]
Traceback (most recent call last):
  File "./main.py", line 44, in _process
    trade = create_trade(float(_CONF['stake_amount']), exchange.EXCHANGE)
  File "./main.py", line 204, in create_trade
    if get_buy_signal(_pair):
  File "/Users/John/Documents/GitHub/freqtrade/analyze.py", line 264, in get_buy_signal
    dataframe = analyze_ticker(pair)
  File "/Users/John/Documents/GitHub/freqtrade/analyze.py", line 252, in analyze_ticker
    data = get_ticker(pair, minimum_date)
  File "/Users/John/Documents/GitHub/freqtrade/analyze.py", line 35, in get_ticker
    data = requests.get(url, params=params, headers=headers).json()
  File "/Users/John/Documents/GitHub/freqtrade/.env/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The bot keeps running but throws this error periodically after going through buy signals but not every iteration.

**Comment by clarkjw4** [comment]
More detailed version of when the error first occurred and how it progressed...

2017-10-17 15:30:27,884 - __main__ - INFO - *BITTREX:* Scooping [BTC/DGB](https://bittrex.com/Market/Index?MarketName=BTC-DGB) for the low `0.000002`
2017-10-17 15:30:51,126 - rpc.telegram - INFO - Executing handler: _status for chat_id: 336462843
2017-10-17 15:30:53,683 - __main__ - INFO - Creating new trade with stake_amount: 0.050000 ...
2017-10-17 15:30:53,868 - __main__ - DEBUG - Ignoring BTC_DGB in pair whitelist
2017-10-17 15:30:53,868 - __main__ - DEBUG - Ignoring USDT_BTC in pair whitelist
2017-10-17 15:31:06,390 - analyze - DEBUG - buy_trigger: 2017-10-17T21:25:00 (pair=BTC_1ST, signal=False)
2017-10-17 15:31:19,068 - analyze - DEBUG - buy_trigger: 2017-10-17T21:25:00 (pair=BTC_ADA, signal=False)
2017-10-17 15:31:31,506 - analyze - DEBUG - buy_trigger: 2017-10-17T21:25:00 (pair=BTC_ADT, signal=False)
2017-10-17 15:31:44,725 - analyze - DEBUG - buy_trigger: 2017-10-17T21:25:00 (pair=BTC_ADX, signal=False)
2017-10-17 15:31:57,783 - analyze - DEBUG - buy_trigger: 2017-10-17T21:25:00 (pair=BTC_ARK, signal=False)
2017-10-17 15:32:10,591 - analyze - DEBUG - buy_trigger: 2017-10-17T21:25:00 (pair=BTC_BAT, signal=False)
2017-10-17 15:32:23,587 - analyze - DEBUG - buy_trigger: 2017-10-17T21:25:00 (pair=BTC_BCC, signal=False)
2017-10-17 15:32:32,686 - rpc.telegram - INFO - Executing handler: _status for chat_id: 336462843
2017-10-17 15:32:36,493 - analyze - DEBUG - buy_trigger: 2017-10-17T21:25:00 (pair=BTC_EMC2, signal=False)
2017-10-17 15:32:49,438 - analyze - DEBUG - buy_trigger: 2017-10-17T21:25:00 (pair=BTC_ETC, signal=False)
2017-10-17 15:33:02,537 - analyze - DEBUG - buy_trigger: 2017-10-17T21:30:00 (pair=BTC_ETH, signal=False)
2017-10-17 15:33:16,353 - analyze - DEBUG - buy_trigger: 2017-10-17T21:25:00 (pair=BTC_FUN, signal=False)
2017-10-17 15:33:39,260 - analyze - DEBUG - buy_trigger: 2017-10-17T21:30:00 (pair=BTC_LMC, signal=False)
2017-10-17 15:33:52,326 - analyze - DEBUG - buy_trigger: 2017-10-17T21:30:00 (pair=BTC_LSK, signal=False)
2017-10-17 15:49:44,345 - analyze - DEBUG - buy_trigger: 2017-10-17T21:45:00 (pair=BTC_PAY, signal=False)
2017-10-17 15:49:57,359 - analyze - DEBUG - buy_trigger: 2017-10-17T21:45:00 (pair=BTC_PIVX, signal=False)
2017-10-17 15:50:10,464 - analyze - DEBUG - buy_trigger: 2017-10-17T21:45:00 (pair=BTC_QTUM, signal=False)
2017-10-17 15:50:22,424 - analyze - DEBUG - buy_trigger: 2017-10-17T21:45:00 (pair=BTC_SALT, signal=False)
2017-10-17 15:50:35,322 - analyze - DEBUG - buy_trigger: 2017-10-17T21:45:00 (pair=BTC_STRAT, signal=False)
2017-10-17 15:50:48,076 - analyze - DEBUG - buy_trigger: 2017-10-17T21:45:00 (pair=BTC_SYS, signal=False)
2017-10-17 15:51:01,022 - analyze - DEBUG - buy_trigger: 2017-10-17T21:45:00 (pair=BTC_VTC, signal=False)
2017-10-17 15:51:01,401 - __main__ - ERROR - Unable to create trade
Traceback (most recent call last):
  File "./main.py", line 44, in _process
    trade = create_trade(float(_CONF['stake_amount']), exchange.EXCHANGE)
  File "./main.py", line 204, in create_trade
    if get_buy_signal(_pair):
  File "/Users/John/Documents/GitHub/freqtrade/analyze.py", line 264, in get_buy_signal
    dataframe = analyze_ticker(pair)
  File "/Users/John/Documents/GitHub/freqtrade/analyze.py", line 252, in analyze_ticker
    data = get_ticker(pair, minimum_date)
  File "/Users/John/Documents/GitHub/freqtrade/analyze.py", line 35, in get_ticker
    data = requests.get(url, params=params, headers=headers).json()
  File "/Users/John/Documents/GitHub/freqtrade/.env/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2017-10-17 15:51:01,721 - __main__ - DEBUG - Handling open trade Trade(id=7, pair=BTC_DGB, amount=27472.527472527476, open_rate=1.82e-06, open_since=closed) ...
2017-10-17 15:51:01,954 - __main__ - DEBUG - Need more gainz. (cur_profit: 0.55%)
2017-10-17 15:51:26,966 - __main__ - INFO - Creating new trade with stake_amount: 0.050000 ...
2017-10-17 15:51:27,503 - __main__ - DEBUG - Ignoring USDT_BTC in pair whitelist
.................................................................................
2017-10-17 20:55:41,092 - analyze - DEBUG - buy_trigger: 2017-10-18T02:50:00 (pair=BTC_XEM, signal=False)
2017-10-17 20:55:54,314 - analyze - DEBUG - buy_trigger: 2017-10-18T02:50:00 (pair=BTC_XLM, signal=False)
2017-10-17 20:56:07,280 - analyze - DEBUG - buy_trigger: 2017-10-18T02:50:00 (pair=BTC_XMR, signal=False)
2017-10-17 20:56:20,183 - analyze - DEBUG - buy_trigger: 2017-10-18T02:50:00 (pair=BTC_XRP, signal=False)
2017-10-17 20:58:00,394 - __main__ - ERROR - Unable to create trade
Traceback (most recent call last):
  File "./main.py", line 44, in _process
    trade = create_trade(float(_CONF['stake_amount']), exchange.EXCHANGE)
  File "./main.py", line 204, in create_trade
    if get_buy_signal(_pair):
  File "/Users/John/Documents/GitHub/freqtrade/analyze.py", line 264, in get_buy_signal
    dataframe = analyze_ticker(pair)
  File "/Users/John/Documents/GitHub/freqtrade/analyze.py", line 252, in analyze_ticker
    data = get_ticker(pair, minimum_date)
  File "/Users/John/Documents/GitHub/freqtrade/analyze.py", line 35, in get_ticker
    data = requests.get(url, params=params, headers=headers).json()
  File "/Users/John/Documents/GitHub/freqtrade/.env/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2017-10-17 20:58:25,400 - __main__ - INFO - Creating new trade with stake_amount: 0.050000 ...
2017-10-17 20:58:25,689 - __main__ - DEBUG - Ignoring USDT_BTC in pair whitelist
........................................................................................
2017-10-17 22:52:50,248 - __main__ - ERROR - Unable to create trade
Traceback (most recent call last):
  File "./main.py", line 44, in _process
    trade = create_trade(float(_CONF['stake_amount']), exchange.EXCHANGE)
  File "./main.py", line 204, in create_trade
    if get_buy_signal(_pair):
  File "/Users/John/Documents/GitHub/freqtrade/analyze.py", line 264, in get_buy_signal
    dataframe = analyze_ticker(pair)
  File "/Users/John/Documents/GitHub/freqtrade/analyze.py", line 252, in analyze_ticker
    data = get_ticker(pair, minimum_date)
  File "/Users/John/Documents/GitHub/freqtrade/analyze.py", line 35, in get_ticker
    data = requests.get(url, params=params, headers=headers).json()
  File "/Users/John/Documents/GitHub/freqtrade/.env/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
..................


It seems to occur every 4 or 5 hours.

**Comment by clarkjw4** [comment]
Implemented Error check in analyze.py line 35-44 get_ticker
