### ISSUE TITLE
BitTrex: Quantity Not Provided

### ISSUE THREAD

**Issue by WaterKH** [clarkjw4/freqtrade#3]
Steps to replicate: Unknown at this time. Probably a null variable being passed to this method.
Potential fix: Just add null/ quantity is greater than 0 check.

```
  File "/Users/John/Desktop/freqtrade-bid-balance/.env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/Users/John/Desktop/freqtrade-bid-balance/.env/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 172, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/Users/John/Desktop/freqtrade-bid-balance/rpc/telegram.py", line 76, in wrapper
    return command_handler(*args, **kwargs)
  File "/Users/John/Desktop/freqtrade-bid-balance/rpc/telegram.py", line 256, in _forcesell
    profit = trade.exec_sell_order(current_rate, balance)
  File "/Users/John/Desktop/freqtrade-bid-balance/persistence.py", line 81, in exec_sell_order
    order_id = exchange.sell(str(self.pair), rate, amount)
  File "/Users/John/Desktop/freqtrade-bid-balance/exchange.py", line 79, in sell
    raise RuntimeError('BITTREX: {}'.format(data['message']))
RuntimeError: BITTREX: QUANTITY_NOT_PROVIDED
```

**Comment by clarkjw4** [comment]
Crashed when I forcesold. When I rebooted the forcesell wasn't recognized and ran a few iterations before crashing again realizing there was no order open

Traceback (most recent call last):
  File "./main.py", line 273, in app
    _process()
  File "./main.py", line 63, in _process
    handle_trade(trade)
  File "./main.py", line 152, in handle_trade
    execute_sell(trade, current_rate)
  File "./main.py", line 116, in execute_sell
    profit = trade.exec_sell_order(current_rate, balance)
  File "/Users/John/Documents/GitHub/freqtrade/persistence.py", line 81, in exec_sell_order
    order_id = exchange.sell(str(self.pair), rate, amount)
  File "/Users/John/Documents/GitHub/freqtrade/exchange.py", line 82, in sell
    raise RuntimeError('BITTREX: {}'.format(data['message']))
RuntimeError: BITTREX: QUANTITY_NOT_PROVIDED

**Comment by clarkjw4** [comment]
Fixed Forcesell issue.
