### ISSUE TITLE
Logger.py

### ISSUE THREAD

**Issue by WaterKH** [clarkjw4/freqtrade#6]
- [x] Logger
- [x] Lines of deprecated fixed EX. **** MA = pd.stats.moments.rolling_mean(df['close'],k)
/Users/John/Documents/GitHub/freqtrade/analyze.py:142: FutureWarning: pd.rolling_std is deprecated for Series and will be removed in a future version, replace with 
	Series.rolling(window=20,center=False).std()***
- [x] Cancel Order Function in telegram.py (Will post error traceback when it occurs again)

**Comment by clarkjw4** [comment]
```
2017-10-12 20:13:56,611 - rpc.telegram - INFO - *BITTREX:* Cancelling [BTC/XVG]
2017-10-12 20:14:04,544 - __main__ - DEBUG - Handling open trade Trade(id=1, pair=BTC_SC, amount=62500.00000000001, open_rate=8e-07, open_since=closed) ...
2017-10-12 20:14:04,748 - __main__ - DEBUG - Need more gainz. (cur_profit: -2.50%)
2017-10-12 20:14:05,155 - __main__ - DEBUG - Handling open trade Trade(id=3, pair=BTC_XVG, amount=55555.55555555556, open_rate=9e-07, open_since=closed) ...
2017-10-12 20:14:05,406 - __main__ - DEBUG - Need more gainz. (cur_profit: 0.00%)
2017-10-12 20:14:31,165 - __main__ - DEBUG - Handling open trade Trade(id=1, pair=BTC_SC, amount=62500.00000000001, open_rate=8e-07, open_since=closed) ...
2017-10-12 20:14:31,406 - __main__ - DEBUG - Need more gainz. (cur_profit: -2.50%)
2017-10-12 20:14:31,701 - __main__ - DEBUG - Handling open trade Trade(id=3, pair=BTC_XVG, amount=55555.55555555556, open_rate=9e-07, open_since=closed) ...
2017-10-12 20:14:31,932 - __main__ - DEBUG - Need more gainz. (cur_profit: 0.00%)
2017-10-12 20:14:57,103 - __main__ - DEBUG - Handling open trade Trade(id=1, pair=BTC_SC, amount=62500.00000000001, open_rate=8e-07, open_since=closed) ...
2017-10-12 20:14:57,335 - __main__ - DEBUG - Need more gainz. (cur_profit: -2.50%)
2017-10-12 20:14:57,515 - __main__ - DEBUG - Handling open trade Trade(id=3, pair=BTC_XVG, amount=55555.55555555556, open_rate=9e-07, open_since=closed) ...
2017-10-12 20:14:58,372 - __main__ - ERROR - RuntimeError. Trader stopped!
Traceback (most recent call last):
  File "./main.py", line 274, in app
    _process()
  File "./main.py", line 64, in _process
    handle_trade(trade)
  File "./main.py", line 153, in handle_trade
    execute_sell(trade, current_rate)
  File "./main.py", line 117, in execute_sell
    profit = trade.exec_sell_order(current_rate, balance)
  File "/Users/John/Documents/GitHub/freqtrade/persistence.py", line 81, in exec_sell_order
    order_id = exchange.sell(str(self.pair), rate, amount)
  File "/Users/John/Documents/GitHub/freqtrade/exchange.py", line 82, in sell
    raise RuntimeError('BITTREX: {}'.format(data['message']))
RuntimeError: BITTREX: QUANTITY_NOT_PROVIDED
```

**Comment by clarkjw4** [comment]
- [x] Telegram Command to log instance
- [x] Logger contents: info when you type command /profit on telegram Date, Time, Trade count, Best performing trade, Average duration, ROI (return on investment). Also I would like the BTC and USD value of my bitrrex wallet and then the price of BTC. And then errors if that's possible too
- [x] Log every 6 hours

**Comment by clarkjw4** [comment]
Logger is funcional
