### ISSUE TITLE
Cancel Order: Not working

### ISSUE THREAD

**Issue by WaterKH** [clarkjw4/freqtrade#8]
@clarkjw4 Add description of how this is supposed to work.

**Comment by clarkjw4** [comment]
2017-10-15 22:01:26,521 - rpc.telegram - INFO - Executing handler: _cancelorder for chat_id: 336462843
BTC_STRAT
2017-10-15 22:01:27,260 - rpc.telegram - INFO - *BITTREX:* Cancelling [BTC/STRAT]
2017-10-15 22:01:28,294 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Users/John/Documents/GitHub/freqtrade/.env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/Users/John/Documents/GitHub/freqtrade/.env/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 172, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/Users/John/Documents/GitHub/freqtrade/rpc/telegram.py", line 79, in wrapper
    return command_handler(*args, **kwargs)
  File "/Users/John/Documents/GitHub/freqtrade/rpc/telegram.py", line 344, in _cancelorder
    exchange.cancel_order(trade.open_order_id)
  File "/Users/John/Documents/GitHub/freqtrade/exchange.py", line 129, in cancel_order
    raise RuntimeError('BITTREX: {}'.format(data['message']))
RuntimeError: BITTREX: ORDER_NOT_OPEN
2017-10-15 22:01:35,124 - analyze - DEBUG - buy_trigger: 2017-10-16T03:55:00 (pair=BTC_TRUST, signal=False)
2017-10-15 22:01:48,341 - analyze - DEBUG - buy_trigger: 2017-10-16T03:55:00 (pair=BTC_VTC, signal=False)
2017-10-15 22:02:04,554 - analyze - DEBUG - buy_trigger: 2017-10-16T03:55:00 (pair=BTC_XMR, signal=False)
2017-10-15 22:02:21,019 - analyze - DEBUG - buy_trigger: 2017-10-16T03:55:00 (pair=BTC_XRP, signal=False)
2017-10-15 22:02:33,212 - analyze - DEBUG - buy_trigger: 2017-10-16T03:55:00 (pair=BTC_DNT, signal=False)
2017-10-15 22:02:33,213 - root - INFO - Streets askin too high...
2017-10-15 22:02:33,505 - __main__ - DEBUG - Handling open trade Trade(id=2, pair=BTC_STRAT, amount=97.04403858470975, open_rate=0.00051523, open_since=closed) ...
2017-10-15 22:02:34,386 - __main__ - ERROR - RuntimeError. Trader stopped!
Traceback (most recent call last):
  File "./main.py", line 275, in app
    _process()
  File "./main.py", line 64, in _process
    handle_trade(trade)
  File "./main.py", line 154, in handle_trade
    execute_sell(trade, current_rate)
  File "./main.py", line 118, in execute_sell
    profit = trade.exec_sell_order(current_rate, balance)
  File "/Users/John/Documents/GitHub/freqtrade/persistence.py", line 81, in exec_sell_order
    order_id = exchange.sell(str(self.pair), rate, amount)
  File "/Users/John/Documents/GitHub/freqtrade/exchange.py", line 82, in sell
    raise RuntimeError('BITTREX: {}'.format(data['message']))
RuntimeError: BITTREX: QUANTITY_NOT_PROVIDED

**Comment by clarkjw4** [comment]
Trade ID: 2
Current Pair: BTC_STRAT (https://bittrex.com/Market/Index?MarketName=BTC-STRAT)
Open Since: 5 hours ago
Amount: 97.04403858
Open Rate: 0.00051523
Close Rate: None
Current Rate: 0.000528
Close Profit: None
Current Profit: 2.48%
Open Order: 97.04403858 (LIMIT_BUY)

This is the order that was not filled. As you can see the amount and the open order are the same. This means that no coins were purchased. It cancels on bittrex, and telegram sends a message that it is canceling but when it gets back to the order after checking buy signals it crashes with the above error

**Comment by clarkjw4** [comment]
[ ]Needs Testing

**Comment by clarkjw4** [comment]
Traceback (most recent call last):
  File "/Users/John/Documents/GitHub/freqtrade/.env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/Users/John/Documents/GitHub/freqtrade/.env/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 172, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/Users/John/Documents/GitHub/freqtrade/rpc/telegram.py", line 84, in wrapper
    return command_handler(*args, **kwargs)
  File "/Users/John/Documents/GitHub/freqtrade/rpc/telegram.py", line 273, in _cancelorder
    trade = Trade.query.filter(and_(
NameError: name 'and_' is not defined

**Comment by clarkjw4** [comment]
Imported _and

**Comment by clarkjw4** [comment]
Error for Cancel Order

ile "/Users/John/Documents/GitHub/freqtrade/rpc/telegram.py", line 295, in _cancelorder
    closed = close_trade_if_fulfilled(trade)
