### ISSUE TITLE
Inputs are all NaN

### ISSUE THREAD

**Issue by clarkjw4** [clarkjw4/freqtrade#9]
```
2017-10-14 22:47:07,057 - analyze - DEBUG - buy_trigger: 2017-10-15T04:40:00 (pair=BTC_CLAM, signal=False)
2017-10-14 22:47:20,040 - analyze - DEBUG - buy_trigger: 2017-10-15T04:40:00 (pair=BTC_CVC, signal=False)
Traceback (most recent call last):
  File "./main.py", line 302, in <module>
    app(_CONF)
  File "./main.py", line 275, in app
    _process()
  File "./main.py", line 44, in _process
    trade = create_trade(float(_CONF['stake_amount']), exchange.EXCHANGE)
  File "./main.py", line 204, in create_trade
    if get_buy_signal(_pair):
  File "/Users/John/Documents/GitHub/freqtrade/analyze.py", line 264, in get_buy_signal
    dataframe = analyze_ticker(pair)
  File "/Users/John/Documents/GitHub/freqtrade/analyze.py", line 254, in analyze_ticker
    dataframe = populate_indicators(dataframe)
  File "/Users/John/Documents/GitHub/freqtrade/analyze.py", line 63, in populate_indicators
    dataframe['ema'] = ta.EMA(dataframe, timeperiod=33)
  File "talib/abstract.pyx", line 358, in talib.abstract.Function.__call__ (talib/abstract.c:6913)
  File "talib/abstract.pyx", line 389, in talib.abstract.Function.__call_function (talib/abstract.c:7620)
  File "talib/func.pyx", line 7092, in talib.func.EMA (talib/func.c:79408)
Exception: inputs are all NaN
d
```

**Comment by clarkjw4** [comment]
New error noticed before #9 error was thrown. It was thown 20 times in about 22 minutes before it crashed on error #9. It was throwing it at different intervals and currencies.

Traceback (most recent call last):
  File "./main.py", line 55, in _process
    trade = create_trade(float(_CONF['stake_amount']), exchange.EXCHANGE)
  File "./main.py", line 247, in create_trade
    if get_buy_signal(_pair):
  File "/Users/John/Documents/GitHub/freqtrade/analyze.py", line 205, in get_buy_signal
    dataframe = analyze_ticker(pair)
  File "/Users/John/Documents/GitHub/freqtrade/analyze.py", line 189, in analyze_ticker
    dataframe = parse_ticker_dataframe(data['result'], minimum_date)
  File "/Users/John/Documents/GitHub/freqtrade/analyze.py", line 77, in parse_ticker_dataframe
    .drop('BV', 1) \
  File "/Users/John/Documents/GitHub/freqtrade/.env/lib/python3.6/site-packages/pandas/core/generic.py", line 2161, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/John/Documents/GitHub/freqtrade/.env/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3624, in drop
    labels[mask])
ValueError: labels ['BV'] not contained in axis
